name: CI Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
   environment: test
    runs-on: ubuntu-latest
    continue-on-error: true

    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"

      - name: Install dependencies
        run: npm install

      - name: DB Cleaning
        run: npm run db-clean

      - name: DB Seeding
        run: npm run db-seed

      - name: Run linter
        run: npm run fixlint && npm run lint

      - name: Run tests
        run: npm run test
  merge:
      needs: [test]
      environment: test
      runs-on: ubuntu-latest
      steps:
        - name: Merge
          run: echo "Can Be Merge..."
    report:
      needs: merge
      if: failure()
      runs-on: ubuntu-latest
      steps:
        - name: Output information
          run: |
            echo "Something went wrong"
            echo "${{ toJSON(github) }}"