name: Lint and Test When There's Push in Main

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    environment: test
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      IMAGEKIT_PUBLIC_KEY: ${{ secrets.IMAGEKIT_PUBLIC_KEY }}
      IMAGEKIT_PRIVATE_KEY: ${{ secrets.IMAGEKIT_PRIVATE_KEY }}
      IMAGEKIT_URL: ${{ secrets.IMAGEKIT_URL }}
      MIDTRANS_MERCHANT_ID: ${{ secrets.MIDTRANS_MERCHANT_ID }}
      MIDTRANS_CLIENT_KEY: ${{ secrets.MIDTRANS_CLIENT_KEY }}
      MIDTRANS_SERVER_KEY: ${{ secrets.MIDTRANS_SERVER_KEY }}
      APP_EMAIL_ADDRESS: ${{ secrets.APP_EMAIL_ADDRESS }}
      APP_EMAIL_PASSWORD: ${{ secrets.APP_EMAIL_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRES: ${{ secrets.JWT_EXPIRES }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      PORT: 3000
      BASE_URL: localhost:3000
      NODE_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Cleaning DB
        run: npm run db-clean

      - name: Seed database
        run: npm run db-seed

      - name: Run tests
        id: run-tests
        run: npm run test

  lint:
    name: Lint Code
    needs: test
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-modules-

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run fixlint

  merge:
    name: Merge Code
    needs: [test, lint]
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        run: echo "Ready to merge..."

  report:
    name: Report Issues
    needs: merge
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong"
          echo "${{ toJSON(github) }}"
